# Generated by Django 5.2.3 on 2025-06-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='country',
            field=models.CharField(blank=True, help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='current_download_speed',
            field=models.FloatField(blank=True, help_text='Current download speed in Mbps', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='current_latency',
            field=models.FloatField(blank=True, help_text='Current latency in ms', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='current_upload_speed',
            field=models.FloatField(blank=True, help_text='Current upload speed in Mbps', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, help_text='Device hostname', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='isp',
            field=models.CharField(blank=True, help_text='Internet Service Provider', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='last_traceroute',
            field=models.DateTimeField(blank=True, help_text='Last traceroute execution', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='traceroute_hops',
            field=models.JSONField(blank=True, default=list, help_text='Traceroute hop information'),
        ),
    ]
