# Generated by Django 5.2.3 on 2025-06-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_city_device_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('server', 'Server'), ('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('printer', 'Printer'), ('workstation', 'Workstation'), ('dns_server', 'DNS Server'), ('web_server', 'Web Server'), ('database', 'Database'), ('ftp_server', 'FTP Server'), ('load_balancer', 'Load Balancer'), ('other', 'Other')], default='server', help_text='Type of device', max_length=20),
        ),
    ]
